// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxfrintflnnfgpwjlzmp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4ZnJpbnRmbG5uZmdwd2psem1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTY5NTQsImV4cCI6MjA2NDk3Mjk1NH0.PoXWznueyxDSb9CWXMOfYptuAcusko_uo5GEoTovaR4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});